#!/bin/bash
#
# Changes security settings for all PNG files
#

# Load tools library
WORKSPACE=~/Projects/Trace
. ${WORKSPACE}/_/tools.inc

# Create files
FixSec() {
    printf "Modifying files...\n";
    ls *.png > png.list
    while read a 
    do
        echo "$a";
        chmod ugo+rw "$a";
    done < png.list
}

main() {
    FixSec "$@"
}

main "$@"

